const MODULE_NAME = 'COMMON';

export const START_FETCHING = `${MODULE_NAME}/START_FETCHING`;
export const STOP_FETCHING = `${MODULE_NAME}/STOP_FETCHING`;
export const ERROR_FETCHING = `${MODULE_NAME}/ERROR_FETCHING`;
export const SUCCESS_FETCHING = `${MODULE_NAME}/SUCCESS_FETCHING`;
